import test from 'node:test';
import assert from 'node:assert/strict';
import {createState,saveLot,evolvePrices,ledger} from '../dist/domain.js';
import {transact,eligibleBuyers} from '../dist/transactions.js';
const now='2026-09-11T10:00:00.000Z';
function setup(){const state=createState(now);const lot=saveLot(state,{materialId:'cables',locality:'Mumbai',weight:'12.5',photoId:'photo-test'},{publish:true,now});return {state,lot,run:(type,input={})=>transact(state,{type,lotId:lot.id,input},now)};}
function ready(){const s=setup();const offer=s.run('offer',{buyerId:'buyer-green'});s.run('accept',{offerId:offer.id});s.run('schedule',{slot:'2026-09-12T10:00:00Z',instructions:'Test depot'});s.run('advance');s.run('advance');return {...s,offer};}
test('one accepted offer and frozen rate after market moves',()=>{const {state,lot,run}=setup();const a=run('offer',{buyerId:'buyer-green'}),b=run('offer',{buyerId:'buyer-circle'});const rate=a.ratePaise;run('accept',{offerId:a.id});assert.throws(()=>run('accept',{offerId:b.id}));evolvePrices(state,'2026-09-11T10:02:00Z');assert.equal(a.ratePaise,rate);assert.equal(lot.acceptedOfferId,a.id);assert.equal(b.status,'rejected');});
test('ineligible buyer and stale lot action rejected',()=>{const {state,lot,run}=setup();lot.locality='Thane';assert(!eligibleBuyers(lot).some(b=>b.id==='buyer-circle'));assert.throws(()=>run('offer',{buyerId:'buyer-circle'}));assert.throws(()=>transact(state,{type:'offer',lotId:lot.id,expectedVersion:0,input:{buyerId:'buyer-green'}}));});
test('reschedule retains history and arrival cannot be skipped',()=>{const {state,run}=setup();const o=run('offer',{buyerId:'buyer-green'});run('accept',{offerId:o.id});run('schedule',{slot:'2026-09-12T10:00:00Z',instructions:'Depot'});run('schedule',{slot:'2026-09-13T10:00:00Z',instructions:'Depot B'});assert.equal(state.pickups[0].history.length,1);assert.throws(()=>run('handover',{weight:'10',photoId:'photo-x',location:'Depot'}));assert.throws(()=>run('schedule',{slot:now,instructions:'Depot'}));});
test('disputed evidence retained; payment cannot precede confirmation or exceed dues',()=>{const {state,run,offer}=ready();const first=run('handover',{weight:'10',photoId:'photo-a',location:'Depot'});assert.throws(()=>run('payment',{amount:'1'}));run('dispute',{reason:'Scale reads 11 kg'});const second=run('handover',{weight:'11',photoId:'photo-b',location:'Depot'});assert.equal(first.status,'superseded');assert.equal(first.grams,10000);run('confirm');assert.throws(()=>run('confirm'));assert.equal(second.finalValuePaise,offer.ratePaise*11);assert.throws(()=>run('payment',{amount:String(second.finalValuePaise/100+1)}));run('payment',{amount:'100'});assert.equal(ledger(state).receivedPaise,10000);assert.equal(ledger(state).outstandingPaise,second.finalValuePaise-10000);run('payment',{amount:((second.finalValuePaise-10000)/100).toFixed(2)});assert.equal(ledger(state).outstandingPaise,0);assert.equal(state.lots[0].status,'completed');assert.throws(()=>run('payment',{amount:'0.01'}));});
