package com.ewaste.nativeapp;

import android.app.AlertDialog;
import android.content.Intent;
import android.net.Uri;
import android.os.Bundle;
import android.text.InputType;
import android.widget.*;
import org.json.*;
import java.io.File;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.time.Instant;
import java.util.*;
import java.util.function.Consumer;

/** Collector marketplace screens, rendered entirely with Android Views. */
final class CollectorUi {
    final MainActivity a;
    String requirementId="",orderId="",filter="",area="",sort="Relevant",orderFilter="All",scanLotId="";
    CollectorUi(MainActivity activity){a=activity;}
    void save(Bundle out){out.putString("marketRequirement",requirementId);out.putString("marketOrder",orderId);out.putString("marketScan",scanLotId);}
    void restore(Bundle saved){if(saved!=null){requirementId=saved.getString("marketRequirement","");orderId=saved.getString("marketOrder","");scanLotId=saved.getString("marketScan","");}}
    JSONObject market(){JSONObject m=a.shared.optJSONObject("collectorMarket");return m==null?new JSONObject():m;}
    JSONArray array(String key){JSONArray list=market().optJSONArray(key);return list==null?new JSONArray():list;}
    JSONObject find(String key,String id){JSONArray list=array(key);for(int i=0;i<list.length();i++){JSONObject o=list.optJSONObject(i);if(o!=null&&o.optString("id").equals(id))return o;}return null;}
    JSONObject profile(){JSONObject p=market().optJSONObject("profile");return p==null?new JSONObject():p;}
    String locality(){return area.isEmpty()?profile().optString("locality","Mumbai"):area;}
    void go(String screen){a.screen=screen;a.render();}
    void heading(String title,String subtitle){a.add(a.page,a.text(title,27,MainActivity.INK,true));if(!subtitle.isEmpty())a.add(a.page,a.text(subtitle,14,MainActivity.MUTED,false));}
    void note(LinearLayout box,String text){a.add(box,a.text(text,14,MainActivity.MUTED,false));}
    void action(LinearLayout box,String label,String tag,Runnable action,boolean primary){a.action(box,label,tag,action,primary);}
    void show(String screen){
        if(a.store.pendingMarket()!=null)action(a.page,"Retry pending action","retry-market",this::retry,true);
        switch(screen){case "orders":orders();break;case "order":order();break;case "contacts":contacts();break;case "profile":profileView();break;case "requirement":requirement();break;case "matches":matches();break;case "notifications":notifications();break;case "safety":safety();break;default:home();}
    }
    void refresh(){a.refreshWorkspace(true);}
    void home(){
        scanLotId="";
        heading("Hello, "+profile().optString("name","Collector"),"Find demand. Compare quotes. Give e-waste its next step.");
        LinearLayout hero=a.card(a.page);hero.setBackground(a.background(MainActivity.GREEN));a.add(hero,a.text("What have you collected?",23,android.graphics.Color.WHITE,true));a.add(hero,a.text("Scan it, confirm the category and explore recycler offers.",15,android.graphics.Color.WHITE,false));action(hero,"＋ Scan / create a lot","create-lot",()->{scanLotId="";a.startCreate();},false);
        action(a.page,"Notifications","notifications",()->go("notifications"),false);
        JSONArray orders=array("orders");for(int i=0;i<orders.length();i++){JSONObject o=orders.optJSONObject(i);if(o!=null&&!Arrays.asList("completed","cancelled").contains(o.optString("status"))){orderCard(o);break;}}
        a.add(a.page,a.text("Recycler requirements",22,MainActivity.INK,true));note(a.page,"Demo marketplace · illustrative quotes, no real recycler verification or payment.");
        action(a.page,"Filter: "+(filter.isEmpty()?"All categories":Catalog.name(filter))+" · "+locality(),"filter-market",this::filters,false);
        action(a.page,"Sort: "+sort,"sort-market",()->new AlertDialog.Builder(a).setTitle("Sort comparable quotes").setItems(new String[]{"Relevant","Price high to low","Price low to high"},(d,i)->{sort=new String[]{"Relevant","Price high to low","Price low to high"}[i];a.render();}).show(),false);
        renderRequirements(false);action(a.page,"Refresh requirements","refresh-market",this::refresh,false);action(a.page,"Hygiene & safety","home-safety",()->go("safety"),false);
    }
    boolean active(JSONObject r){try{return r.optString("status").equals("active")&&Instant.parse(r.optString("expiresAt")).isAfter(Instant.now());}catch(Exception e){return false;}}
    boolean serves(JSONObject r){JSONArray list=r.optJSONArray("serviceAreas");if(list!=null)for(int i=0;i<list.length();i++)if(list.optString(i).equals(locality()))return true;return false;}
    Set<String> matchingCodes(){if(a.draft==null)return Collections.emptySet();JSONObject d=a.draft.optJSONObject("wasteDecision");return d==null?Collections.emptySet():Catalog.codes(d.optJSONArray("codes"));}
    boolean matchesCategory(JSONObject r,Set<String> codes){Set<String> allowed=Catalog.codes(r.optJSONArray("codes"));if(allowed.isEmpty()||codes.isEmpty())return true;for(String c:codes)if(allowed.contains(c))return true;return false;}
    List<JSONObject> requirements(boolean matching){List<JSONObject> list=new ArrayList<>();Set<String> codes=matching?matchingCodes():filter.isEmpty()?Collections.emptySet():Collections.singleton(filter);JSONArray all=array("requirements");for(int i=0;i<all.length();i++){JSONObject r=all.optJSONObject(i);if(r!=null&&active(r)&&serves(r)&&matchesCategory(r,codes))list.add(r);}
        list.sort((x,y)->{if(!sort.equals("Relevant")){int group=x.optString("material").compareTo(y.optString("material"));if(group!=0)return group;group=x.optString("unit").compareTo(y.optString("unit"));if(group!=0)return group;int by=Double.compare(x.optDouble("quotedPricePaise"),y.optDouble("quotedPricePaise"));return sort.equals("Price high to low")?-by:by;}boolean genericX=Catalog.codes(x.optJSONArray("codes")).isEmpty(),genericY=Catalog.codes(y.optJSONArray("codes")).isEmpty();return Boolean.compare(genericX,genericY);});return list;}
    void renderRequirements(boolean matching){List<JSONObject> list=requirements(matching);if(list.isEmpty()){note(a.page,a.workspaceCode.isEmpty()?"Connect your workspace to load recycler requirements.":"No active requirements match this category and service area. Save a general lot or try another filter.");action(a.page,"Connect / refresh","empty-connect",this::refresh,false);}for(JSONObject r:list)requirementCard(r);if(!sort.equals("Relevant"))note(a.page,"Prices are sorted within the same material and unit. ₹/kg and ₹/piece are not directly comparable.");}
    void requirementCard(JSONObject r){LinearLayout c=a.card(a.page);JSONObject recycler=find("recyclers",r.optString("recyclerId"));a.add(c,a.text(r.optString("material"),21,MainActivity.INK,true));note(c,(recycler==null?"Recycler":recycler.optString("name"))+" · Demo, unverified");a.add(c,a.text(a.money(r.optDouble("quotedPricePaise"))+" / "+r.optString("unit"),25,MainActivity.GREEN,true));note(c,"Required: "+r.optString("minQuantity")+"–"+r.optString("maxQuantity")+" "+r.optString("unit")+" · "+r.optString("pickupMode").replace('_',' '));note(c,locality()+" service area · valid until "+r.optString("expiresAt").split("T")[0]);action(c,"View requirement","requirement-"+r.optString("id"),()->{requirementId=r.optString("id");go("requirement");},true);}
    void filters(){List<String> labels=new ArrayList<>();labels.add("All categories");labels.addAll(Arrays.asList(Catalog.NAMES));new AlertDialog.Builder(a).setTitle("Category").setItems(labels.toArray(new String[0]),(d,i)->{filter=i==0?"":Catalog.code(i-1);new AlertDialog.Builder(a).setTitle("Service area").setItems(Catalog.LOCALITIES,(dialog,j)->{area=Catalog.LOCALITIES[j];a.render();}).show();}).show();}
    void startMatches(){
        if(a.draft==null||a.draft.optJSONObject("wasteDecision")==null)return;
        try{a.store.saveDraft(a.draft);a.dirty=false;scanLotId=a.draft.optString("id");area=a.draft.optString("locality","Mumbai");go("matches");}catch(Exception e){a.alert("Could not save draft",e.getMessage());}
    }
    void matches(){heading("Matching recycler offers","Confirm the exact requested item before ordering. A broad category alone does not determine its price.");if(a.draft==null){scanLotId="";note(a.page,"Open your saved scan to restore its category selection.");action(a.page,"Saved lots","saved-lots",()->go("lots"),true);return;}note(a.page,"Confirmed: "+Catalog.names(matchingCodes()));action(a.page,"Back to scan","back-scan",()->go("create"),false);renderRequirements(true);action(a.page,"Safety for this collection","matched-safety",()->go("safety"),false);}
    void requirement(){JSONObject r=find("requirements",requirementId);if(r==null){heading("Requirement unavailable","Refresh your workspace and try again.");action(a.page,"Refresh","refresh",this::refresh,true);return;}
        heading(r.optString("material"),"Recycler requirement · demo quote");JSONObject recycler=find("recyclers",r.optString("recyclerId"));LinearLayout c=a.card(a.page);a.add(c,a.text(recycler==null?"Recycler":recycler.optString("name"),21,MainActivity.GREEN,true));note(c,"Demo listing — authorization has not been verified.");a.add(c,a.text(a.money(r.optDouble("quotedPricePaise"))+" / "+r.optString("unit"),28,MainActivity.GREEN,true));note(c,"Quantity: "+r.optString("minQuantity")+"–"+r.optString("maxQuantity")+" "+r.optString("unit"));note(c,"Service areas: "+join(r.optJSONArray("serviceAreas")));note(c,"Mode: "+r.optString("pickupMode").replace('_',' ')+" · expiry: "+r.optString("expiresAt").split("T")[0]);note(c,"Final payout uses the accepted unit price and confirmed received quantity. This quote is not a guaranteed payout.");
        for(int i=0;i<array("contacts").length();i++){JSONObject prior=array("contacts").optJSONObject(i);if(prior!=null&&prior.optString("requirementId").equals(requirementId))note(c,"Previous interaction: "+prior.optString("status").replace('_',' '));}
        if(active(r)&&serves(r)){action(a.page,"Contact recycler · demo","contact-recycler",()->submit("market_contact",object("requirementId",requirementId),"contacts"),false);action(a.page,"Create demo order","create-order",()->orderForm(r),true);}else note(a.page,"This requirement has expired, closed or does not serve the selected area. Ordering is disabled.");
        note(a.page,"Demo contact records an interaction only. No call or message is sent.");action(a.page,"Report an issue","report",()->prompt("Describe the issue","",text->submit("market_report",object("requirementId",requirementId,"reason",text),"requirement")),false);action(a.page,"Hygiene & safety","requirement-safety",()->go("safety"),false);action(a.page,"Back to offers","back-offers",()->go(!scanLotId.isEmpty()?"matches":"home"),false);
    }
    String join(JSONArray values){List<String> s=new ArrayList<>();if(values!=null)for(int i=0;i<values.length();i++)s.add(values.optString(i));return String.join(", ",s);}
    JSONObject object(Object... pairs){JSONObject o=new JSONObject();for(int i=0;i<pairs.length;i+=2)Catalog.put(o,(String)pairs[i],pairs[i+1]);return o;}
    void orderForm(JSONObject r){
        LinearLayout box=a.column();box.setPadding(a.dp(22),a.dp(8),a.dp(22),a.dp(8));note(box,"Quantity in "+r.optString("unit")+" · "+a.money(r.optDouble("quotedPricePaise"))+" per "+r.optString("unit"));
        EditText qty=new EditText(a);qty.setTag("order-quantity");qty.setHint("Quantity");qty.setInputType(InputType.TYPE_CLASS_NUMBER|(r.optString("unit").equals("kg")?InputType.TYPE_NUMBER_FLAG_DECIMAL:0));box.addView(qty);TextView total=a.text("Enter quantity for estimated total",18,MainActivity.GREEN,true);box.addView(total);
        qty.addTextChangedListener(new android.text.TextWatcher(){public void beforeTextChanged(CharSequence s,int st,int count,int after){}public void onTextChanged(CharSequence s,int st,int before,int count){try{double q=Double.parseDouble(s.toString());total.setText("Estimated: "+a.money(q*r.optDouble("quotedPricePaise")));}catch(Exception e){total.setText("Enter a valid quantity");}}public void afterTextChanged(android.text.Editable e){}});
        CheckBox confirm=new CheckBox(a);confirm.setText("I confirm these items are "+r.optString("material")+".");confirm.setTag("material-confirmation");box.addView(confirm);note(box,"Service area: "+locality()+". This creates a demo request. No money is transferred.");
        AlertDialog dialog=new AlertDialog.Builder(a).setTitle("Review demo order").setView(box).setPositiveButton("Request order",null).setNegativeButton("Cancel",null).create();dialog.setOnShowListener(v->dialog.getButton(-1).setOnClickListener(button->{String q=qty.getText().toString().trim();if(!confirm.isChecked()){a.toast("Confirm the requested material first");return;}try{double n=Double.parseDouble(q);if(!q.matches(r.optString("unit").equals("piece")?"\\d+":"\\d+(\\.\\d{1,3})?")||n<r.optDouble("minQuantity")||n>r.optDouble("maxQuantity"))throw new Exception();}catch(Exception e){qty.setError("Use "+r.optString("minQuantity")+"–"+r.optString("maxQuantity")+" "+r.optString("unit"));return;}
            JSONObject input=object("requirementId",r.optString("id"),"quoteVersion",r.optInt("version"),"quantity",q,"unit",r.optString("unit"),"locality",locality(),"materialConfirmed",true);
            if(!scanLotId.isEmpty()&&a.draft!=null&&a.draft.optString("id").equals(scanLotId)){for(String key:new String[]{"photoId","wasteAssessment","wasteDecision"})if(a.draft.has(key))Catalog.put(input,key,a.draft.opt(key));}
            dialog.dismiss();submit("market_order",input,"order");}));dialog.show();
    }
    void orders(){heading("Orders","Track requests, agreed values and received quantities.");action(a.page,"Saved lots & drafts","saved-lots",()->go("lots"),false);action(a.page,"Show: "+orderFilter,"order-filter",()->new AlertDialog.Builder(a).setTitle("Order status").setItems(new String[]{"All","Active","Completed","Cancelled"},(d,i)->{orderFilter=new String[]{"All","Active","Completed","Cancelled"}[i];a.render();}).show(),false);int count=0;JSONArray list=array("orders");for(int i=0;i<list.length();i++){JSONObject o=list.optJSONObject(i);String status=o.optString("status");boolean show=orderFilter.equals("All")||orderFilter.equals("Active")&&!Arrays.asList("completed","cancelled").contains(status)||orderFilter.equalsIgnoreCase(status);if(show){orderCard(o);count++;}}if(count==0)note(a.page,"No orders in this view. Open a recycler requirement to create one.");action(a.page,"Refresh orders","refresh-orders",this::refresh,false);}
    void orderCard(JSONObject o){LinearLayout c=a.card(a.page);a.add(c,a.text(o.optString("material"),20,MainActivity.INK,true));note(c,o.optString("recyclerName")+" · "+o.optString("status").toUpperCase(Locale.ROOT));note(c,o.optString("quantity")+" "+o.optString("unit")+" × "+a.money(o.optDouble("unitPricePaise"))+" · "+o.optString("createdAt").split("T")[0]);a.add(c,a.text(a.money(o.has("finalTotalPaise")?o.optDouble("finalTotalPaise"):o.optDouble("estimatedTotalPaise"))+(o.has("finalTotalPaise")?" confirmed value":" estimated"),20,MainActivity.GREEN,true));action(c,"View order","order-"+o.optString("id"),()->{orderId=o.optString("id");go("order");},false);}
    void order(){JSONObject o=find("orders",orderId);if(o==null){heading("Order unavailable","Refresh orders to get the latest status.");action(a.page,"Orders","all-orders",()->go("orders"),true);return;}heading(o.optString("material"),o.optString("id"));note(a.page,o.optString("recyclerName")+" · "+o.optString("locality")+" · "+o.optString("pickupMode").replace('_',' '));LinearLayout c=a.card(a.page);note(c,"Requested: "+o.optString("quantity")+" "+o.optString("unit")+" at "+a.money(o.optDouble("unitPricePaise"))+" / "+o.optString("unit"));if(o.has("confirmedQuantity"))note(c,"Received: "+o.optString("confirmedQuantity")+" "+o.optString("unit"));a.add(c,a.text(a.money(o.has("finalTotalPaise")?o.optDouble("finalTotalPaise"):o.optDouble("estimatedTotalPaise"))+(o.has("finalTotalPaise")?" final value":" estimated"),25,MainActivity.GREEN,true));note(c,"Status: "+o.optString("status").toUpperCase(Locale.ROOT));if(o.has("paidPaise"))note(c,"Demo payment recorded: "+a.money(o.optDouble("paidPaise"))+". No money transferred.");
        JSONArray timeline=o.optJSONArray("timeline");if(timeline!=null)for(int i=0;i<timeline.length();i++){JSONObject e=timeline.optJSONObject(i);a.add(a.page,a.text("● "+e.optString("status").replace('_',' '),17,MainActivity.GREEN,true));note(a.page,e.optString("at").replace('T',' ')+"\n"+e.optString("note"));}
        String status=o.optString("status");String next=status.equals("requested")?"accepted":status.equals("accepted")?"pickup":status.equals("pickup")?"received":status.equals("received")?"completed":"";
        if(!next.isEmpty()){action(a.page,"Demo: mark "+next,"advance-order",()->{if(next.equals("received"))prompt("Confirm received quantity ("+o.optString("unit")+")",o.optString("quantity"),q->submit("market_order_status",object("orderId",orderId,"expectedVersion",o.optInt("version"),"status",next,"confirmedQuantity",q),"order"));else new AlertDialog.Builder(a).setTitle("Simulate "+next+"?").setMessage("This is a demo status update. No recycler is contacted and no payment is made.").setPositiveButton("Update",(d,w)->submit("market_order_status",object("orderId",orderId,"expectedVersion",o.optInt("version"),"status",next),"order")).setNegativeButton("Cancel",null).show();},true);action(a.page,"Cancel order","cancel-order",()->prompt("Cancellation reason","",reason->submit("market_order_status",object("orderId",orderId,"expectedVersion",o.optInt("version"),"status","cancelled","note",reason),"order")),false);}
        action(a.page,"All orders","all-orders",()->go("orders"),false);
    }
    void contacts(){heading("Contacted recyclers","Interactions are separate from completed orders. These are demo records; no messages are sent.");List<JSONObject> list=new ArrayList<>();JSONArray all=array("contacts");for(int i=0;i<all.length();i++)list.add(all.optJSONObject(i));list.sort((x,y)->y.optString("lastInteractionAt").compareTo(x.optString("lastInteractionAt")));if(list.isEmpty())note(a.page,"No contacts yet. Open a recycler requirement and use Contact recycler.");for(JSONObject contact:list){JSONObject r=find("requirements",contact.optString("requirementId")),recycler=find("recyclers",contact.optString("recyclerId"));LinearLayout c=a.card(a.page);a.add(c,a.text(recycler==null?"Recycler":recycler.optString("name"),20,MainActivity.INK,true));note(c,contact.optString("status").replace('_',' ')+" · "+contact.optString("lastInteractionAt").split("T")[0]);if(r!=null){note(c,r.optString("material")+" · "+a.money(r.optDouble("quotedPricePaise"))+" / "+r.optString("unit"));action(c,"Resume requirement","resume-contact",()->{scanLotId="";requirementId=r.optString("id");go("requirement");},false);}if(contact.has("orderId"))action(c,"Open order","contact-order",()->{orderId=contact.optString("orderId");go("order");},false);action(c,"Update demo interaction","contact-status",()->new AlertDialog.Builder(a).setTitle("Interaction status").setItems(new String[]{"Responded","Negotiating","Closed"},(d,i)->submit("market_contact_status",object("contactId",contact.optString("id"),"status",new String[]{"responded","negotiating","closed"}[i]),"contacts")).show(),false);}}
    void profileView(){heading("Profile",profile().optString("name","Collector")+" · "+profile().optString("locality","Mumbai"));double paid=0;int completed=0;JSONArray list=array("orders");for(int i=0;i<list.length();i++){JSONObject o=list.optJSONObject(i);if(o.optString("status").equals("completed")){completed++;paid+=o.optDouble("paidPaise");}}LinearLayout c=a.card(a.page);a.add(c,a.text(completed+" completed orders",20,MainActivity.INK,true));a.add(c,a.text(a.money(paid)+" demo earnings",27,MainActivity.GREEN,true));note(c,"No money is transferred. Existing lot earnings are available below.");action(a.page,"Edit profile","edit-profile",this::editProfile,false);action(a.page,"Workspace connection","connect",a::connectionDialog,true);note(a.page,"Shared demo workspace · English interface. Individual phone OTP accounts are not enabled.");action(a.page,"Existing lot earnings","legacy-earnings",()->go("wallet"),false);action(a.page,"Saved lots and drafts","saved-lots",()->go("lots"),false);action(a.page,"Indicative material prices","legacy-prices",()->go("prices"),false);action(a.page,"Notifications","profile-notifications",()->go("notifications"),false);action(a.page,"Hygiene & safety","profile-safety",()->go("safety"),false);action(a.page,"Help","help",()->a.alert("Demo help","Scan an item, confirm its category, compare requirements and create a demo request. For connection issues, retry with your workspace code. Do not enter the Gemini API key here."),false);}
    void editProfile(){LinearLayout fields=a.column();fields.setPadding(a.dp(22),a.dp(10),a.dp(22),a.dp(10));EditText name=new EditText(a);name.setHint("Collector name");name.setText(profile().optString("name",""));fields.addView(name);Spinner place=new Spinner(a);place.setAdapter(new ArrayAdapter<>(a,android.R.layout.simple_spinner_dropdown_item,Catalog.LOCALITIES));place.setSelection(Math.max(0,Arrays.asList(Catalog.LOCALITIES).indexOf(profile().optString("locality"))));fields.addView(place);new AlertDialog.Builder(a).setTitle("Collector profile").setView(fields).setPositiveButton("Save",(d,w)->submit("market_profile",object("name",name.getText().toString(),"locality",Catalog.LOCALITIES[place.getSelectedItemPosition()]),"profile")).setNegativeButton("Cancel",null).show();}
    void notifications(){heading("Notifications","Order updates and saved interactions in this workspace.");JSONArray list=array("notifications");if(list.length()==0)note(a.page,"You are up to date. New order and contact events appear here after refresh.");for(int i=0;i<list.length();i++){JSONObject n=list.optJSONObject(i);LinearLayout c=a.card(a.page);a.add(c,a.text((n.optBoolean("read")?"":"● ")+n.optString("title"),17,MainActivity.INK,true));note(c,n.optString("createdAt").replace('T',' '));action(c,"Open","open-notification",()->{if(n.optString("target").equals("order"))orderId=n.optString("targetId");else{requirementId=n.optString("targetId");scanLotId="";}submit("market_notification_read",object("notificationId",n.optString("id")),n.optString("target").equals("order")?"order":"requirement");},false);}action(a.page,"Refresh notifications","refresh-notifications",this::refresh,false);}
    void safety(){heading("Hygiene & safe handling","Basic precautions. Ask the manufacturer or an authorized handler about damaged or unfamiliar equipment.");String[][] cards={{"DO · Use a separate collection route","Keep lithium batteries and devices containing them out of ordinary rubbish and mixed municipal recycling."},{"DO · Protect intact battery terminals","For an intact, removable battery, cover exposed terminals with non-conductive tape or keep each battery in its own bag."},{"DON’T · Treat swelling as normal","A swollen battery is damaged and may be a fire hazard. Stop routine handling and seek manufacturer or specialist advice."},{"DON’T · Force a battery out","Some batteries are not designed for removal. Follow the product’s markings and manufacturer instructions."},{"DO · Protect batteries from damage","Avoid crushing or puncturing batteries during collection and transport."},{"DON’T · Leave batteries in extreme heat","Avoid prolonged heat, including a vehicle dashboard in direct sunlight."},{"DO · Ask before transporting damaged batteries","Obtain specific handling guidance from the battery or device manufacturer."},{"DO · Escalate signs of fire","If there is smoke, fire or an immediate threat, move away and contact local emergency services. Do not handle the device."}};for(String[] card:cards){LinearLayout c=a.card(a.page);a.add(c,a.text(card[0],18,MainActivity.GREEN,true));note(c,card[1]);}note(a.page,"Sources: US EPA battery handling guidance. Check local collection arrangements with an authorized handler.");action(a.page,"Read battery handling guidance","safety-source",()->a.startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse("https://www.epa.gov/recycle/used-lithium-ion-batteries"))),false);action(a.page,"Damaged battery guidance","safety-source-damaged",()->a.startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse("https://www.epa.gov/recycle/frequent-questions-lithium-ion-batteries"))),false);if(a.draft!=null)action(a.page,"Return to scan","safety-back",()->go("create"),true);}
    void prompt(String title,String initial,Consumer<String> done){EditText input=new EditText(a);input.setText(initial);input.setPadding(a.dp(22),a.dp(12),a.dp(22),a.dp(12));new AlertDialog.Builder(a).setTitle(title).setView(input).setPositiveButton("Continue",(d,w)->done.accept(input.getText().toString().trim())).setNegativeButton("Cancel",null).show();}
    String fingerprint(String code)throws Exception{byte[] hash=MessageDigest.getInstance("SHA-256").digest(code.getBytes(StandardCharsets.UTF_8));StringBuilder value=new StringBuilder();for(byte b:hash)value.append(String.format(Locale.ROOT,"%02x",b&255));return value.toString();}
    void submit(String type,JSONObject input,String destination){if(a.working)return;if(a.workspaceCode.isEmpty()){a.connectionDialog();return;}try{if(a.store.pendingMarket()!=null){a.alert("Action waiting for retry","Retry the saved action before submitting another.");return;}JSONObject pending=object("body",object("operationId","operation-"+UUID.randomUUID(),"command",object("type",type,"input",input)),"workspaceHash",fingerprint(a.workspaceCode),"destination",destination);a.store.setPendingMarket(pending);retry();}catch(Exception e){a.alert("Could not save action",e.getMessage());}}
    void retry(){if(a.working)return;JSONObject pending=a.store.pendingMarket();if(pending==null)return;if(a.workspaceCode.isEmpty()){a.connectionDialog();return;}String code=a.workspaceCode;try{if(!pending.optString("workspaceHash").equals(fingerprint(code))){a.alert("Different workspace","Reconnect the workspace used for this pending action before retrying.");return;}}catch(Exception e){a.alert("Connection error",e.getMessage());return;}a.working=true;a.render();
        a.task(()->{JSONObject body=pending.getJSONObject("body"),input=body.getJSONObject("command").getJSONObject("input");String photo=input.optString("photoId");if(!photo.isEmpty()){File f=a.store.photo(photo);if(!f.exists())a.api.download(photo,code,f);a.api.upload(f,photo,code);}JSONObject result=a.api.json("POST","/api/commands",code,body).getJSONObject("result");JSONObject state=a.api.json("GET","/api/state",code,null).getJSONObject("state");a.store.setShared(state);a.store.setPendingMarket(null);return object("state",state,"result",result);},response->{a.shared=response.optJSONObject("state");a.working=false;a.connectionNotice="";JSONObject result=response.optJSONObject("result");if(result!=null&&result.optString("id").startsWith("order-")){orderId=result.optString("id");scanLotId="";}go(pending.optString("destination","home"));},error->{a.working=false;if(error instanceof ApiClient.ApiException){int status=((ApiClient.ApiException)error).status;if(status>=400&&status<500&&status!=408&&status!=429){try{a.store.setPendingMarket(null);}catch(Exception ignored){}a.render();a.alert("Please review this action",error.getMessage());return;}}a.connectionNotice="Connection interrupted · your action is saved for retry";a.render();a.alert("Saved for retry",error.getMessage()+" Retry uses the same request ID to avoid duplicate orders.");});
    }
}
