package com.ewaste.nativeapp;

import android.app.AlertDialog;
import android.content.Intent;
import android.net.Uri;
import android.text.InputType;
import android.widget.*;
import org.json.*;
import java.net.URLEncoder;
import java.util.*;

/** Authorized directory, posted lots and the existing request/quote conversation. */
final class DiscoveryScreens {
 final MarketplaceScreens m;final AccountActivity a;final AccountDesign ui;
 DiscoveryScreens(MarketplaceScreens market){m=market;a=m.a;ui=a.ui;}
 String enc(String s){try{return URLEncoder.encode(s,"UTF-8");}catch(Exception e){throw new IllegalArgumentException(e);}}
 JSONObject filter(){try{JSONObject p=a.store.cached(a.account(),"discovery-filter");if(p==null)p=new JSONObject();if(p.optInt("filterVersion")<2){p.put("filterVersion",2);p.put("radius",0);remember(p);}return p;}catch(Exception e){return new JSONObject();}}
 void remember(JSONObject f){a.store.cache(a.account(),"discovery-filter",f);}
 void open(boolean directory){search(directory,0);}
 String locationQuery(){JSONObject f=filter(),p=f.optJSONObject("location");if(p!=null)return "&lat="+p.optDouble("latitude")+"&lon="+p.optDouble("longitude");return f.optBoolean("noOrigin")?"&location=off":"";}
 void detail(boolean directory,String id){m.load(directory?"recycler-detail":"listing",(directory?"/directory/":"/listings/")+id+"?view=detail"+locationQuery());}
 JSONObject currentOrigin(){JSONObject selected=filter().optJSONObject("location");return selected!=null?selected:m.data().optJSONObject("origin");}
 void directions(JSONObject target){try{JSONObject point=target.optJSONObject("location"),from=currentOrigin();String destination=point==null?target.optString("address")+" "+target.optString("locality"):point.optDouble("latitude")+","+point.optDouble("longitude");String url="https://www.google.com/maps/dir/?api=1&travelmode=driving&destination="+enc(destination);if(from!=null)url+="&origin="+enc(from.optDouble("latitude")+","+from.optDouble("longitude"));a.startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse(url)));}catch(Exception e){a.showError(e);}}

 void search(boolean directory,int page){JSONObject f=filter();String path=(directory?"/directory":"/listings")+"?page="+page+"&search="+enc(f.optString("search"))+"&material="+enc(f.optString("material"));path+=locationQuery();if(f.optInt("radius",0)>0)path+="&radius="+f.optInt("radius");if(directory&&f.optBoolean("pickup"))path+="&pickup=true";m.load(directory?"directory":"discover",path);}
 void filters(boolean directory)throws Exception{JSONObject f=filter();LinearLayout card=ui.card(a.page,AccountDesign.WHITE);ui.inside(card,()->{
  a.field(a.t("Search name, city or area"),f.optString("search"),"discovery-search",InputType.TYPE_CLASS_TEXT,120,v->{m.put(f,"search",v);remember(f);});
  if(f.optBoolean("expanded")){String[] names=new String[Catalog.NAMES.length+1];names[0]=a.t("All materials");System.arraycopy(Catalog.NAMES,0,names,1,Catalog.NAMES.length);int selected=0;for(int i=0;i<Catalog.NAMES.length;i++)if(Catalog.code(i).equals(f.optString("material")))selected=i+1;
  a.choices(a.t("Material"),names,selected,pos->{m.put(f,"material",pos==0?"":Catalog.code(pos-1));remember(f);});
  if(directory){CheckBox pickup=new CheckBox(a);pickup.setText(a.t("Pickup available"));pickup.setChecked(f.optBoolean("pickup"));card.addView(pickup);pickup.setOnCheckedChangeListener((b,on)->{m.put(f,"pickup",on);remember(f);});}
  a.choices(a.t("Search radius"),new String[]{a.t("Any distance"),"10 km","25 km","50 km","100 km","250 km","500 km"},Math.max(0,Arrays.asList(0,10,25,50,100,250,500).indexOf(f.optInt("radius",0))),pos->{m.put(f,"radius",new int[]{0,10,25,50,100,250,500}[pos]);remember(f);});}
 });
 ui.action(card,a.t(f.optBoolean("expanded")?"Hide filters":"Material, distance and pickup filters"),"discovery-filters",()->{m.put(f,"expanded",!f.optBoolean("expanded"));remember(f);a.render();},0);
 LinearLayout actions=ui.row();card.addView(actions);Button gps=ui.action(actions,a.t("Use my location"),"discovery-gps",()->a.nearby.get(point->{m.put(f,"location",point);f.remove("noOrigin");remember(f);search(directory,0);}),0);LinearLayout.LayoutParams gp=new LinearLayout.LayoutParams(0,-2,1);gp.rightMargin=a.dp(6);gps.setLayoutParams(gp);
 Button search=ui.action(actions,a.t("Search"),"discovery-apply",()->search(directory,0),1);search.setLayoutParams(new LinearLayout.LayoutParams(0,-2,1));
 ui.action(card,a.t("Choose my city or area"),"discovery-area",()->a.nearby.chooseArea(a.session.optJSONObject("user").optString("locality"),point->{m.put(f,"location",point);f.remove("noOrigin");remember(f);search(directory,0);}),0);
 JSONObject from=currentOrigin();if(from!=null){ui.note(card,a.t("Distance from:")+" "+from.optString("label",a.t("Selected location")));ui.note(card,a.t("Approximate straight-line distance. Open directions for the road route."));ui.action(card,a.t("Clear location"),"discovery-clear-location",()->{f.remove("location");m.put(f,"noOrigin",true);remember(f);search(directory,0);},0);}else ui.note(card,a.t("Choose your location to see distances."));

 }
 String distance(JSONObject d){return !d.has("distanceKm")||d.isNull("distanceKm")?a.t("Distance unavailable"):a.t("About ")+d.optInt("distanceKm")+" km · "+a.t("straight-line");}
 void results(JSONObject d,boolean directory)throws Exception{
  ui.heading(a.t(directory?"Authorized recyclers":"Posted materials"),a.t(directory?"Find a registered recycler for your collection.":"Discover available lots and send a material offer."));filters(directory);
  JSONArray entries=d.optJSONArray(directory?"recyclers":"lots");if(entries==null||entries.length()==0){LinearLayout empty=ui.card(a.page,AccountDesign.SOFT);ui.note(empty,a.t(directory?"No authorized recyclers match these filters yet.":"No posted lots match these filters yet."));}
  if(entries!=null)for(int i=0;i<entries.length();i++){JSONObject r=entries.getJSONObject(i);LinearLayout card=ui.card(a.page,AccountDesign.WHITE);card.addView(ui.text(r.optString(directory?"name":"title"),20,AccountDesign.INK,true));ui.note(card,r.optString("locality"));if(!directory)ui.note(card,r.optString("aggregator"));ui.note(card,distance(r));if(directory){ui.pill(card,a.t("Authorization checked"),AccountDesign.SOFT);ui.note(card,a.t(r.optBoolean("pickup")?"Pickup available":"Contact for handover options"));}ui.action(card,a.t(directory?"View recycler":"View lot"),"discovery-open-"+i,()->detail(directory,r.optString("id")),1);}
  if(!d.isNull("nextPage")&&d.has("nextPage"))ui.action(a.page,a.t("Next page"),"discovery-next",()->search(directory,d.optInt("nextPage")),0);
 }
 void recycler(JSONObject d)throws Exception{JSONObject r=d.optJSONObject("recycler");if(r==null)return;ui.heading(r.optString("name"),r.optString("locality"));LinearLayout card=ui.card(a.page,AccountDesign.WHITE);ui.note(card,distance(r));ui.action(card,a.t("Directions"),"recycler-directions",()->directions(r),0);
  for(String[] field:new String[][]{{"address","Facility address"},{"contact","Business contact"},{"phone","Business phone"},{"email","Business email"},{"hours","Operating hours"},{"areas","Service areas"}})if(!r.optString(field[0]).isEmpty())ui.keyValue(card,a.t(field[1]),r.optString(field[0]));
  ui.note(card,m.facility.categoryNames(Catalog.codes(r.optJSONArray("categories"))));ui.note(card,a.t(r.optBoolean("pickup")?"Pickup available":"Contact for handover options"));
  JSONObject auth=r.getJSONObject("authorization");LinearLayout approval=ui.card(a.page,AccountDesign.SOFT);ui.pill(approval,a.t("Authorization checked"),AccountDesign.WHITE);ui.note(approval,auth.optString("authority")+" · "+auth.optString("registration"));ui.note(approval,a.t("Valid until: ")+a.localDate(auth.optString("validUntil")));ui.note(approval,a.t("Source: ")+auth.optString("source"));
  String phone=r.optString("phone");if(!phone.isEmpty())ui.action(a.page,a.t("Call recycler"),"directory-call",()->{try{a.startActivity(new Intent(Intent.ACTION_DIAL,Uri.fromParts("tel",phone,null)));}catch(Exception e){a.showError(e);}},0);
  ui.action(a.page,a.t("Chat with recycler"),"directory-chat",()->m.chat.chooseLot(r.optString("recyclerId")),1);ui.section(a.t("Current offered rates"));JSONArray rates=r.optJSONArray("rates");if(rates==null||rates.length()==0)ui.note(a.page,a.t("No current rate. Check again after the recycler publishes requirements."));
  if(rates!=null)for(int i=0;i<rates.length();i++){JSONObject rate=rates.getJSONObject(i);LinearLayout row=ui.card(a.page,AccountDesign.WHITE);row.addView(ui.text(rate.optString("title"),18,AccountDesign.INK,true));ui.keyValue(row,"₹"+rate.optString("rate")+" / "+a.t(rate.optString("unit")),a.t("Minimum: ")+rate.optString("minimum"));ui.note(row,a.t("Valid until: ")+a.localDate(rate.optString("validUntil")));}
  ui.note(a.page,a.t("Rates are indicative. Recycler pays logistics separately."));ui.action(a.page,a.t("Send a lot"),"directory-send-lot",()->chooseLot(r.optString("id")),1);
 }
 void chooseLot(String facilityId){try{JSONArray lots=a.store.drafts(a.account());List<JSONObject> saved=new ArrayList<>();List<String> names=new ArrayList<>();for(int i=0;i<lots.length();i++){JSONObject lot=lots.getJSONObject(i);if(lot.optString("syncState").equals("synced")){saved.add(lot);names.add(lot.optString("title"));}}if(saved.isEmpty()){a.showError(new Exception(a.t("Save a lot online before sending it.")));return;}new AlertDialog.Builder(a).setTitle(a.t("Choose a lot")).setItems(names.toArray(new String[0]),(d,index)->{try{a.draft=saved.get(index);JSONArray items=a.draft.getJSONArray("items");String[] labels=new String[items.length()];for(int i=0;i<labels.length;i++)labels[i]=items.getJSONObject(i).optString("name",items.getJSONObject(i).optString("description"));new AlertDialog.Builder(a).setTitle(a.t("Choose material")).setItems(labels,(di,pos)->{a.itemIndex=pos;m.findMatches(facilityId);}).setNegativeButton(a.t("Back"),null).show();}catch(Exception e){a.showError(e);}}).setNegativeButton(a.t("Back"),null).show();}catch(Exception e){a.showError(e);}}
 void listing(JSONObject d)throws Exception{JSONObject lot=d.optJSONObject("lot");if(lot==null)return;ui.heading(lot.optString("title"),lot.optString("locality"));boolean collector=a.session.optJSONObject("user").optString("role").equals("collector");if(!collector){ui.note(a.page,lot.optString("aggregator"));ui.note(a.page,distance(lot));ui.action(a.page,a.t("Directions"),"listing-directions",()->directions(lot),0);}
  if(collector){android.widget.Button delete=ui.action(a.page,a.t("Delete lot"),"listing-delete",()->a.deleteLot(lot),0);delete.setTextColor(0xffa52b2b);}
  if(!collector)ui.action(a.page,a.t("Chat with aggregator"),"listing-chat",()->m.chat.start(lot.optString("id"),a.account()),1);
  JSONArray photos=lot.optJSONArray("fileIds");if(photos!=null)for(int i=0;i<photos.length();i++){String file=photos.getString(i);ui.action(a.page,a.t("View photo ")+(i+1),"listing-photo-"+i,()->{String token=a.token();a.task(()->a.api.listingPhoto(lot.optString("id"),file,token),bytes->{ImageView image=new ImageView(a);image.setImageBitmap(android.graphics.BitmapFactory.decodeByteArray(bytes,0,bytes.length));image.setAdjustViewBounds(true);new AlertDialog.Builder(a).setView(image).setPositiveButton(a.t("Close"),null).show();});},0);}
  JSONArray items=lot.getJSONArray("items");for(int i=0;i<items.length();i++){JSONObject item=items.getJSONObject(i);LinearLayout card=ui.card(a.page,AccountDesign.WHITE);card.addView(ui.text(item.optString("name").isEmpty()?a.t(Catalog.name(item.optString("broadCode"))):item.optString("name"),20,AccountDesign.INK,true));ui.note(card,a.t(Catalog.name(item.optString("broadCode")))+" · "+item.optString("available")+" "+a.t(item.optString("unit")));ui.note(card,item.optString("description"));ui.note(card,a.t(item.optString("condition")));if(collector){final int line=i;ui.inside(card,()->a.field(a.t("Your asking price ₹ /")+" "+a.t(item.optString("unit")),item.isNull("askingRate")?"":item.optString("askingRate"),"listing-price-"+line,InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_FLAG_DECIMAL,11,value->{m.put(item,"askingRate",value);m.persist();}));ui.note(card,a.t("Optional. This price is negotiable; logistics is separate."));}else ui.keyValue(card,a.t("Aggregator asking price"),item.isNull("askingRate")||item.optString("askingRate").isEmpty()?a.t("Price on request"):"₹"+item.optString("askingRate")+" / "+a.t(item.optString("unit")));if(!collector&&new java.math.BigDecimal(item.optString("available","0")).signum()>0)ui.action(card,a.t("Make an offer"),"listing-offer-"+i,()->offer(lot,item),1);}
  if(collector){JSONObject listing=d.getJSONObject("listing");ui.pill(a.page,a.t(listing.optString("state")),AccountDesign.SOFT);if(!listing.optBoolean("current"))ui.note(a.page,a.t("The saved lot changed. Review and post it again to make it visible."));JSONObject point=lot.optJSONObject("location");if(point!=null)ui.note(a.page,a.t("Approximate location added"));ui.action(a.page,a.t("Use pickup location"),"listing-location",()->a.nearby.get(p->{m.put(lot,"location",p);m.persist();a.render();}),0);ui.action(a.page,a.t("Choose pickup city or area"),"listing-area",()->a.nearby.chooseArea(lot.optString("locality"),p->{m.put(lot,"location",p);m.persist();a.render();}),0);ui.action(a.page,a.t("Remove location"),"listing-clear",()->{m.put(lot,"location",JSONObject.NULL);m.persist();a.render();},0);
   ui.action(a.page,a.t("Post for recyclers"),"listing-publish",()->new AlertDialog.Builder(a).setTitle(a.t("Publish this lot?" )).setMessage(a.t("Share these material details, photos and approximate collection location with registered recyclers. Private notes stay private.")).setPositiveButton(a.t("Post lot"),(di,w)->saveListing(lot,listing,"posted")).setNegativeButton(a.t("Back"),null).show(),1);
   if(listing.optInt("version")>0){ui.action(a.page,a.t("Pause listing"),"listing-pause",()->saveListing(lot,listing,"paused"),0);ui.action(a.page,a.t("Withdraw listing"),"listing-withdraw",()->saveListing(lot,listing,"withdrawn"),0);}
  }
 }
 void saveListing(JSONObject lot,JSONObject listing,String state){JSONObject input=m.input(listing.optInt("version"));m.put(input,"lotVersion",lot.optInt("lotVersion"));m.put(input,"state",state);m.put(input,"sharePhotos",true);m.put(input,"location",lot.opt("location"));JSONObject rates=new JSONObject();JSONArray items=lot.optJSONArray("items");for(int i=0;items!=null&&i<items.length();i++){JSONObject item=items.optJSONObject(i);String rate=item.isNull("askingRate")?"":item.optString("askingRate").trim();if(!rate.isEmpty()&&(!rate.matches("\\d{1,8}(\\.\\d{1,2})?")||new java.math.BigDecimal(rate).signum()<=0)){a.showError(new Exception(a.t("Enter a positive asking price with at most two decimal places.")));return;}m.put(rates,item.optString("id"),rate);}m.put(input,"askingRates",rates);m.change("/listings/"+lot.optString("id"),"PUT",input,"listing");}
 void offer(JSONObject lot,JSONObject item){String token=a.token();a.task(()->a.api.request("GET","/requirements",token,null),response->{try{JSONArray all=response.getJSONArray("requirements");List<JSONObject> choices=new ArrayList<>();List<String> names=new ArrayList<>();for(int i=0;i<all.length();i++){JSONObject r=all.getJSONObject(i);if(r.optString("state").equals("active")&&r.optString("broadCode").equals(item.optString("broadCode"))&&r.optString("unit").equals(item.optString("unit"))){choices.add(r);names.add(r.optString("title")+" · ₹"+r.optString("rate")+" / "+r.optString("unit"));}}if(choices.isEmpty()){new AlertDialog.Builder(a).setTitle(a.t("Add a matching buying requirement")).setMessage(a.t("Publish a requirement for this material, unit and service area before making an offer.")).setPositiveButton(a.t("Buying portfolio"),(di,w)->m.load("portfolio","/requirements")).setNegativeButton(a.t("Back"),null).show();return;}new AlertDialog.Builder(a).setTitle(a.t("Choose buying requirement")).setItems(names.toArray(new String[0]),(di,index)->{try{JSONObject r=choices.get(index),form=new JSONObject().put("lotId",lot.getString("id")).put("itemId",item.getString("id")).put("lotVersion",lot.getInt("lotVersion")).put("listingVersion",lot.getInt("listingVersion")).put("quantity",item.getString("available")).put("unit",item.getString("unit")).put("askingRate",item.opt("askingRate")).put("requirement",r).put("requestId",UUID.randomUUID().toString()).put("mode",r.getJSONArray("modes").getString(0));m.show("offer-form",form);}catch(Exception e){a.showError(e);}}).setNegativeButton(a.t("Back"),null).show();}catch(Exception e){a.showError(e);}});}
 void offerForm(JSONObject d)throws Exception{ui.heading(a.t("Your material offer"),a.t("Recycler pays logistics separately."));if(!d.isNull("askingRate")&&!d.optString("askingRate").isEmpty())ui.note(a.page,a.t("Aggregator asking price")+": ₹"+d.optString("askingRate")+" / "+a.t(d.optString("unit")));m.textField(d,"quantity",a.t("Quantity"),InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_FLAG_DECIMAL,12);m.review(d);}
 void quote(JSONObject r){LinearLayout form=a.column();EditText amount=new EditText(a),note=new EditText(a);amount.setInputType(InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_FLAG_DECIMAL);amount.setHint(a.t("Total material amount ₹"));note.setHint(a.t("Message to the other party"));form.addView(amount);form.addView(note);new AlertDialog.Builder(a).setTitle(a.t("Send a counteroffer")).setView(form).setPositiveButton(a.t("Send"),(d,w)->{JSONObject input=m.input(r.optInt("version"));m.put(input,"offerVersion",r.optInt("offerVersion",1));m.put(input,"amount",amount.getText().toString());m.put(input,"message",note.getText().toString());m.change("/requests/"+r.optString("id")+"/quote","POST",input,"request");}).setNegativeButton(a.t("Back"),null).show();}
}
