package com.ewaste.nativeapp;

import android.app.AlertDialog;
import android.content.*;
import android.graphics.*;
import android.graphics.drawable.GradientDrawable;
import android.media.ExifInterface;
import android.net.Uri;
import android.os.Bundle;
import android.text.*;
import android.view.*;
import android.widget.*;
import androidx.activity.OnBackPressedCallback;
import androidx.activity.result.ActivityResultLauncher;
import androidx.activity.result.contract.ActivityResultContracts;
import androidx.appcompat.app.AppCompatActivity;
import androidx.core.content.FileProvider;
import androidx.core.view.ViewCompat;
import androidx.core.view.WindowInsetsCompat;
import org.json.*;
import java.io.*;
import java.text.NumberFormat;
import java.time.Instant;
import java.util.*;
import java.util.concurrent.*;
import java.util.function.Consumer;

/** All screens are Android Views. No HTML, browser engine, or Capacitor bridge is used. */
public final class MainActivity extends AppCompatActivity {
    static final int GREEN=Color.rgb(18,91,70),LIME=Color.rgb(197,247,121),INK=Color.rgb(30,48,40),MUTED=Color.rgb(101,118,109),BG=Color.rgb(244,247,244),LINE=Color.rgb(218,229,221);
    final ExecutorService tasks=Executors.newSingleThreadExecutor();
    LocalStore store;
    ApiClient api=new ApiClient();
    String workspaceCode="",screen="home",detailId="",photoError="",pendingCameraId="";
    JSONObject shared=new JSONObject(),draft;
    Set<String> selectedCodes=new LinkedHashSet<>();
    boolean dirty=false,working=false,assessmentLoading=false;
    LinearLayout root,page,photoPanel;
    TextView estimateText;
    EditText descriptionInput;
    private final ActivityResultLauncher<String[]> gallery=registerForActivityResult(new ActivityResultContracts.OpenDocument(),uri->{if(uri!=null)processPhoto(uri);});
    private final ActivityResultLauncher<Uri> camera=registerForActivityResult(new ActivityResultContracts.TakePicture(),ok->{if(ok&&!pendingCameraId.isEmpty())processPhoto(Uri.fromFile(store.photo(pendingCameraId)));});

    @Override public void onCreate(Bundle saved){
        super.onCreate(saved);
        try{
            store=new LocalStore(this);workspaceCode=store.code();shared=store.shared();
            if(saved!=null){screen=saved.getString("screen","home");detailId=saved.getString("detail","");pendingCameraId=saved.getString("camera","");String raw=saved.getString("draft");if(raw!=null){draft=new JSONObject(raw);dirty=saved.getBoolean("dirty");JSONArray picked=new JSONArray(saved.getString("selected","[]"));selectedCodes=Catalog.codes(picked);}}
            getOnBackPressedDispatcher().addCallback(this,new OnBackPressedCallback(true){@Override public void handleOnBackPressed(){if(screen.equals("home"))finish();else leaveFor("home");}});
            render();if(!workspaceCode.isEmpty())refreshWorkspace(false);
        }catch(Exception error){new AlertDialog.Builder(this).setTitle("Could not open saved data").setMessage("Your stored files have not been deleted. "+message(error)).setPositiveButton("Close",(d,w)->finish()).show();}
    }
    @Override protected void onSaveInstanceState(Bundle out){super.onSaveInstanceState(out);out.putString("screen",screen);out.putString("detail",detailId);out.putString("camera",pendingCameraId);if(draft!=null){out.putString("draft",draft.toString());out.putString("selected",new JSONArray(selectedCodes).toString());out.putBoolean("dirty",dirty);}}
    @Override protected void onDestroy(){tasks.shutdown();super.onDestroy();}

    private int dp(float value){return Math.round(value*getResources().getDisplayMetrics().density);}
    private String now(){return Instant.now().toString();}
    private String id(String prefix){return prefix+"-"+UUID.randomUUID();}
    private String message(Throwable error){return error.getMessage()==null?error.getClass().getSimpleName():error.getMessage();}
    private String money(double paise){return NumberFormat.getCurrencyInstance(new Locale("en","IN")).format(paise/100);}
    private GradientDrawable background(int color){GradientDrawable d=new GradientDrawable();d.setColor(color);d.setCornerRadius(dp(16));d.setStroke(dp(1),color==Color.WHITE?LINE:color);return d;}
    private LinearLayout column(){LinearLayout v=new LinearLayout(this);v.setOrientation(LinearLayout.VERTICAL);return v;}
    private LinearLayout row(){LinearLayout v=new LinearLayout(this);v.setOrientation(LinearLayout.HORIZONTAL);v.setGravity(Gravity.CENTER_VERTICAL);return v;}
    private TextView text(String value,int size,int color,boolean bold){TextView v=new TextView(this);v.setText(value);v.setTextSize(size);v.setTextColor(color);if(bold)v.setTypeface(null,Typeface.BOLD);v.setPadding(0,dp(5),0,dp(5));return v;}
    private void add(LinearLayout parent,View view){parent.addView(view,new LinearLayout.LayoutParams(-1,-2));}
    private void gap(LinearLayout parent,int height){View space=new View(this);parent.addView(space,new LinearLayout.LayoutParams(1,dp(height)));}
    private LinearLayout card(LinearLayout parent){LinearLayout c=column();c.setPadding(dp(18),dp(15),dp(18),dp(15));c.setBackground(background(Color.WHITE));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.setMargins(0,dp(10),0,dp(4));parent.addView(c,lp);return c;}
    private Button button(String label,String tag,Runnable action,boolean primary){Button b=new Button(this);b.setText(label);b.setAllCaps(false);b.setTag(tag);b.setTextSize(15);b.setTextColor(primary?Color.WHITE:GREEN);b.setBackground(background(primary?GREEN:BG));b.setPadding(dp(12),dp(9),dp(12),dp(9));b.setMinHeight(dp(50));b.setOnClickListener(v->action.run());return b;}
    private void action(LinearLayout parent,String label,String tag,Runnable action,boolean primary){Button b=button(label,tag,action,primary);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.setMargins(0,dp(7),0,dp(4));parent.addView(b,lp);}
    private void alert(String title,String message){if(!isFinishing())new AlertDialog.Builder(this).setTitle(title).setMessage(message).setPositiveButton("OK",null).show();}
    private void toast(String value){Toast.makeText(this,value,Toast.LENGTH_LONG).show();}
    private <T> void task(Callable<T> operation,Consumer<T> success,Consumer<Exception> failure){tasks.submit(()->{try{T value=operation.call();runOnUiThread(()->{if(!isDestroyed()&&!isFinishing())success.accept(value);});}catch(Exception error){runOnUiThread(()->{if(!isDestroyed()&&!isFinishing())failure.accept(error);});}});}
    private void leaveFor(String next){if(dirty&&screen.equals("create")){new AlertDialog.Builder(this).setTitle("Save your lot?").setMessage("You have changes that are not saved.").setPositiveButton("Save draft",(d,w)->saveDraft()).setNegativeButton("Discard changes",(d,w)->{draft=null;dirty=false;screen=next;render();}).setNeutralButton("Keep editing",null).show();}else{screen=next;render();}}

    void render(){
        root=column();root.setBackgroundColor(BG);setContentView(root);
        ViewCompat.setOnApplyWindowInsetsListener(root,(v,insets)->{androidx.core.graphics.Insets bars=insets.getInsets(WindowInsetsCompat.Type.systemBars()|WindowInsetsCompat.Type.ime());v.setPadding(bars.left,bars.top,bars.right,bars.bottom);return insets;});ViewCompat.requestApplyInsets(root);
        LinearLayout header=row();header.setPadding(dp(18),dp(10),dp(12),dp(8));ImageView logo=new ImageView(this);logo.setImageResource(com.ewaste.nativeapp.R.drawable.ic_ewaste);header.addView(logo,new LinearLayout.LayoutParams(dp(35),dp(35)));TextView brand=text("  E-Waste Marketplace",19,GREEN,true);header.addView(brand,new LinearLayout.LayoutParams(0,-2,1));Button settings=button("⚙","settings",this::connectionDialog,false);settings.setContentDescription("Workspace settings");header.addView(settings,new LinearLayout.LayoutParams(dp(52),dp(48)));add(root,header);
        TextView connection=text(workspaceCode.isEmpty()?"  Native Android · Local drafts":"  Native Android · Shared workspace connected",12,MUTED,false);add(root,connection);
        ScrollView scroll=new ScrollView(this);scroll.setFillViewport(true);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));page=column();page.setPadding(dp(18),dp(8),dp(18),dp(20));scroll.addView(page);
        switch(screen){case "create":createView();break;case "lots":lotsView();break;case "prices":pricesView();break;case "wallet":walletView();break;case "detail":detailView();break;default:homeView();}
        if(working)add(page,text("Working…",14,MUTED,false));
        LinearLayout nav=row();nav.setPadding(dp(6),dp(6),dp(6),dp(6));nav.setBackgroundColor(Color.WHITE);String[] ids={"home","prices","lots","wallet"},names={"Home","Prices","My Lots","Earnings"};for(int i=0;i<ids.length;i++){String target=ids[i];Button b=button(names[i],"nav-"+target,()->leaveFor(target),false);b.setTextSize(12);nav.addView(b,new LinearLayout.LayoutParams(0,dp(50),1));}add(root,nav);
    }
    private void homeView(){
        add(page,text("Your material.\nMore possibilities.",28,INK,true));add(page,text("Check local prices and give your e-waste a next step.",15,MUTED,false));
        LinearLayout hero=card(page);hero.setBackground(background(GREEN));add(hero,text("SELL MATERIAL",12,LIME,true));add(hero,text("Turn your next collection into a new lot.",24,Color.WHITE,true));add(hero,text("Take a photo, identify the waste and save your lot.",15,Color.WHITE,false));Button create=button("＋ Create a lot","create-lot",this::startCreate,false);create.setBackground(background(LIME));add(hero,create);
        JSONArray lots=allLots();int drafts=store.drafts().length(),active=0;for(int i=0;i<lots.length();i++){JSONObject lot=lots.optJSONObject(i);if(lot!=null&&!Arrays.asList("draft","completed","cancelled").contains(lot.optString("status")))active++;}
        add(page,text(active+" active lots   ·   "+drafts+" saved drafts",16,GREEN,true));add(page,text("Today’s indicative prices",21,INK,true));priceCards();add(page,text("Your recent lots",21,INK,true));if(lots.length()==0)add(page,text("Your first lot starts here. Use Create a lot above.",15,MUTED,false));for(int i=0;i<Math.min(3,lots.length());i++)lotCard(lots.optJSONObject(i));
    }
    private void pricesView(){add(page,text("Indicative material prices",25,INK,true));add(page,text("Simulated demo prices · ₹ per kg · Mumbai",14,MUTED,false));priceCards();action(page,"Refresh shared prices","refresh-prices",()->refreshWorkspace(true),false);}
    private JSONObject price(String material,String locality){JSONArray prices=shared.optJSONArray("prices");JSONObject found=null;if(prices!=null)for(int i=0;i<prices.length();i++){JSONObject p=prices.optJSONObject(i);if(p!=null&&p.optString("materialId").equals(material)&&p.optString("locality").equals(locality))found=p;}if(found!=null)return found;double base=material.equals("cables")?24500:material.equals("pcb")?38000:9200;JSONObject p=new JSONObject();Catalog.put(p,"lowPaise",base*.9);Catalog.put(p,"highPaise",base*1.1);Catalog.put(p,"ratePaise",base);return p;}
    private void priceCards(){for(int i=1;i<Catalog.MATERIAL_IDS.length;i++){JSONObject p=price(Catalog.MATERIAL_IDS[i],"Mumbai");LinearLayout c=card(page);add(c,text(Catalog.MATERIAL_NAMES[i],18,INK,true));add(c,text(money(p.optDouble("lowPaise"))+" – "+money(p.optDouble("highPaise"))+" / kg",21,GREEN,true));add(c,text("Simulated indicative range · not a buyer quote",12,MUTED,false));}}
    JSONArray allLots(){JSONArray drafts=store.drafts(),remote=shared.optJSONArray("lots"),result=new JSONArray();Set<String> ids=new HashSet<>();for(int i=0;i<drafts.length();i++){JSONObject lot=drafts.optJSONObject(i);if(lot!=null){result.put(lot);ids.add(lot.optString("id"));}}if(remote!=null)for(int i=0;i<remote.length();i++){JSONObject lot=remote.optJSONObject(i);if(lot!=null&&!ids.contains(lot.optString("id")))result.put(lot);}return result;}
    private JSONObject findLot(String id){JSONArray lots=allLots();for(int i=0;i<lots.length();i++){JSONObject lot=lots.optJSONObject(i);if(lot!=null&&lot.optString("id").equals(id))return lot;}return null;}
    private void lotsView(){add(page,text("My lots",27,INK,true));action(page,"＋ Create a lot","create-lot",this::startCreate,true);action(page,"Refresh shared lots","refresh-lots",()->refreshWorkspace(true),false);JSONArray lots=allLots();if(lots.length()==0)add(page,text("No lots yet. Photos and incomplete lots can be saved as drafts.",16,MUTED,false));for(int i=0;i<lots.length();i++)lotCard(lots.optJSONObject(i));}
    private void lotCard(JSONObject lot){if(lot==null)return;LinearLayout c=card(page);add(c,text(Catalog.title(lot),19,INK,true));add(c,text(lot.optString("status","draft").toUpperCase(Locale.ROOT)+" · "+lot.optString("locality","Mumbai"),12,GREEN,true));add(c,text(lot.optString("weight","").isEmpty()?"Weight not recorded":lot.optString("weight")+" kg",15,MUTED,false));if(lot.has("pendingCommand"))add(c,text("Listing is waiting for a connection. Open to retry.",13,MUTED,false));c.setContentDescription("Open lot: "+Catalog.title(lot));c.setOnClickListener(v->{detailId=lot.optString("id");screen="detail";render();});}

    void startCreate(){draft=new JSONObject();Catalog.put(draft,"id",id("lot"));Catalog.put(draft,"locality","Mumbai");Catalog.put(draft,"materialId","");Catalog.put(draft,"weight","");Catalog.put(draft,"description","");Catalog.put(draft,"condition","unsorted");Catalog.put(draft,"status","draft");Catalog.put(draft,"createdAt",now());dirty=false;selectedCodes=new LinkedHashSet<>();photoError="";assessmentLoading=false;screen="create";render();}
    private void editLot(JSONObject lot){draft=Catalog.copy(lot);JSONObject decision=draft.optJSONObject("wasteDecision");selectedCodes=decision==null?Catalog.suggested(draft.optJSONObject("wasteAssessment")):Catalog.codes(decision.optJSONArray("codes"));photoError="";assessmentLoading=false;dirty=false;screen="create";render();}
    private void createView(){
        if(draft==null){startCreate();return;}
        action(page,"‹ Back","back",()->leaveFor("home"),false);add(page,text("Create your lot",26,INK,true));add(page,text("Take or upload a photo. Save an incomplete lot as a draft.",15,MUTED,false));
        LinearLayout c=card(page);add(c,text("Material photo",18,INK,true));String photoId=draft.optString("photoId");if(!photoId.isEmpty())showPhoto(c,photoId);else add(c,text("Add a clear photo of the collected equipment.",15,MUTED,false));
        LinearLayout choices=row();Button take=button("Take photo","take-photo",this::takePhoto,false),choose=button("Choose photo","choose-photo",()->gallery.launch(new String[]{"image/*"}),false);choices.addView(take,new LinearLayout.LayoutParams(0,dp(54),1));choices.addView(choose,new LinearLayout.LayoutParams(0,dp(54),1));add(c,choices);
        photoPanel=column();add(c,photoPanel);renderPhotoPanel();
        LinearLayout fields=card(page);add(fields,text("Lot details",20,INK,true));spinner(fields,"Pricing material",Catalog.MATERIAL_NAMES,Catalog.MATERIAL_IDS,"materialId");add(fields,text("Demo listings currently support cables, circuit boards and motors. Save other equipment as a draft without assigning an incorrect pricing material.",12,MUTED,false));edit(fields,"Approximate weight (kg)","weight",InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_FLAG_DECIMAL);spinner(fields,"Locality",Catalog.LOCALITIES,Catalog.LOCALITIES,"locality");spinner(fields,"Condition",new String[]{"Unsorted","Sorted","Damaged"},Catalog.CONDITIONS,"condition");descriptionInput=edit(fields,"Description","description",InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_FLAG_MULTI_LINE);descriptionInput.setMinLines(2);descriptionInput.setFilters(new InputFilter[]{new InputFilter.LengthFilter(500)});
        estimateText=text("",18,GREEN,true);add(fields,estimateText);updateEstimate();action(page,"Save draft","save-draft",this::saveDraft,true);action(page,"List lot","list-lot",this::publishLot,false);
    }
    private EditText edit(LinearLayout parent,String label,String key,int inputType){add(parent,text(label,14,INK,true));EditText e=new EditText(this);e.setTag(key);e.setContentDescription(label);e.setTextColor(INK);e.setTextSize(16);e.setInputType(inputType);e.setText(draft.optString(key,""));e.setPadding(dp(12),dp(10),dp(12),dp(10));e.setBackground(background(BG));add(parent,e);e.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int start,int count,int after){}public void onTextChanged(CharSequence s,int start,int before,int count){Catalog.put(draft,key,s.toString());dirty=true;if(key.equals("weight"))updateEstimate();}public void afterTextChanged(Editable e){}});gap(parent,8);return e;}
    private void spinner(LinearLayout parent,String label,String[] labels,String[] values,String key){add(parent,text(label,14,INK,true));Spinner spinner=new Spinner(this);spinner.setTag(key);spinner.setContentDescription(label);ArrayAdapter<String> adapter=new ArrayAdapter<>(this,android.R.layout.simple_spinner_item,labels);adapter.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item);spinner.setAdapter(adapter);int selection=Arrays.asList(values).indexOf(draft.optString(key));spinner.setSelection(Math.max(0,selection));add(parent,spinner);spinner.setOnItemSelectedListener(new AdapterView.OnItemSelectedListener(){public void onItemSelected(AdapterView<?> p,View v,int position,long id){if(!draft.optString(key).equals(values[position])){Catalog.put(draft,key,values[position]);dirty=true;updateEstimate();}}public void onNothingSelected(AdapterView<?> p){}});}
    private void updateEstimate(){if(estimateText==null||draft==null)return;double weight=0;try{weight=Double.parseDouble(draft.optString("weight"));}catch(Exception ignored){}String material=draft.optString("materialId");if(weight>0&&!material.isEmpty()){JSONObject p=price(material,draft.optString("locality"));estimateText.setText("Indicative estimate: "+money(p.optDouble("lowPaise")*weight)+" – "+money(p.optDouble("highPaise")*weight)+"\nSimulated · not a buyer quote");}else estimateText.setText("No price estimate until a supported pricing material and weight are entered.");}
    private void renderPhotoPanel(){
        if(photoPanel==null||draft==null||!screen.equals("create"))return;photoPanel.removeAllViews();gap(photoPanel,14);add(photoPanel,text("Waste categories · 20 broad categories",18,INK,true));add(photoPanel,text("Gemini reviews your photo through the connected workspace. Review its suggestion before listing. It does not determine the price.",13,MUTED,false));
        if(workspaceCode.isEmpty())action(photoPanel,"Connect workspace once","connect",this::connectionDialog,false);
        if(assessmentLoading){add(photoPanel,new ProgressBar(this));add(photoPanel,text("Identifying your photo…",15,GREEN,true));}
        if(!photoError.isEmpty())add(photoPanel,text(photoError,14,Color.rgb(170,60,40),false));
        JSONObject a=draft.optJSONObject("wasteAssessment");if(a!=null){add(photoPanel,text("Suggested from your photo",17,INK,true));add(photoPanel,text(a.optString("description"),15,INK,false));JSONArray items=a.optJSONArray("items");if(items!=null)for(int i=0;i<items.length();i++){JSONObject item=items.optJSONObject(i);if(item!=null){add(photoPanel,text("• "+Catalog.name(item.optString("code")),16,GREEN,true));add(photoPanel,text(item.optString("evidence"),13,MUTED,false));}}if(Catalog.suggested(a).isEmpty())add(photoPanel,text("No equipment category identified. Review the photo or choose manually.",14,MUTED,false));if(!a.optString("uncertainty").isEmpty())add(photoPanel,text("Check: "+a.optString("uncertainty"),13,MUTED,false));if(!a.optString("nextPhoto").isEmpty())add(photoPanel,text("More detail: "+a.optString("nextPhoto"),13,MUTED,false));add(photoPanel,text("Gemini · "+a.optString("model"),12,MUTED,false));action(photoPanel,"Use suggested description","use-description",()->{String value=a.optString("description");value=value.substring(0,Math.min(500,value.length()));Catalog.put(draft,"description",value);if(descriptionInput!=null)descriptionInput.setText(value);dirty=true;},false);}
        if(!draft.optString("photoId").isEmpty()&&!assessmentLoading){action(photoPanel,a==null?"Identify photo with Gemini":"Use saved assessment","assess-photo",this::assessPhoto,false);add(photoPanel,text(selectedCodes.isEmpty()?"Choose categories to confirm.":"Selected: "+Catalog.names(selectedCodes),14,INK,false));action(photoPanel,"Choose / change categories","choose-categories",this::chooseCategories,false);action(photoPanel,"Confirm categories","confirm-categories",()->confirmCategories("categories"),true);action(photoPanel,"Not e-waste","not-ewaste",()->confirmCategories("not_ewaste"),false);action(photoPanel,"Needs a better photo","retake",()->confirmCategories("retake_photo"),false);}
        JSONObject d=draft.optJSONObject("wasteDecision");if(d!=null)add(photoPanel,text("Confirmed: "+decisionLabel(d)+" · "+d.optString("method"),14,GREEN,true));
    }
    private String decisionLabel(JSONObject decision){return decision.optString("outcome").equals("categories")?Catalog.names(Catalog.codes(decision.optJSONArray("codes"))):decision.optString("outcome").equals("not_ewaste")?"Not e-waste":"Replace the photo before listing";}
    private void chooseCategories(){boolean[] checked=new boolean[Catalog.NAMES.length];Set<String> next=new LinkedHashSet<>(selectedCodes);for(int i=0;i<checked.length;i++)checked[i]=next.contains(Catalog.code(i));new AlertDialog.Builder(this).setTitle("Visible waste categories").setMultiChoiceItems(Catalog.NAMES,checked,(d,index,on)->{if(on)next.add(Catalog.code(index));else next.remove(Catalog.code(index));}).setPositiveButton("Use selection",(d,w)->{if(next.size()>12){alert("Too many categories","Choose up to 12 visible types in one photo.");return;}selectedCodes=next;draft.remove("wasteDecision");dirty=true;renderPhotoPanel();}).setNegativeButton("Cancel",null).show();}
    void confirmCategories(String outcome){if(draft==null||assessmentLoading)return;if(outcome.equals("categories")&&selectedCodes.isEmpty()){alert("Choose categories","Select at least one category, or mark this photo as not e-waste.");return;}JSONObject a=draft.optJSONObject("wasteAssessment"),d=new JSONObject();Set<String> suggested=Catalog.suggested(a),codes=outcome.equals("categories")?selectedCodes:new LinkedHashSet<>();boolean agrees=outcome.equals("categories")?codes.equals(suggested):outcome.equals("not_ewaste")?a!=null&&a.optString("status").equals("out_of_scope"):a!=null&&Arrays.asList("parts_only","needs_review").contains(a.optString("status"));Catalog.put(d,"photoId",draft.optString("photoId"));Catalog.put(d,"outcome",outcome);Catalog.put(d,"codes",new JSONArray(codes));Catalog.put(d,"method",a==null?"manual":agrees?"confirmed":"corrected");Catalog.put(d,"assessmentId",a==null?null:a.optString("id"));Catalog.put(d,"confirmedAt",now());Catalog.put(draft,"wasteDecision",d);dirty=true;renderPhotoPanel();}

    private void takePhoto(){try{pendingCameraId=id("photo");Uri uri=FileProvider.getUriForFile(this,getPackageName()+".files",store.photo(pendingCameraId));camera.launch(uri);}catch(Exception error){alert("Camera unavailable","Choose an existing photo instead. "+message(error));}}
    void processPhoto(Uri uri){if(draft==null)return;JSONObject target=draft;photoError="Preparing photo…";renderPhotoPanel();task(()->{
        BitmapFactory.Options bounds=new BitmapFactory.Options();bounds.inJustDecodeBounds=true;try(InputStream in=getContentResolver().openInputStream(uri)){BitmapFactory.decodeStream(in,null,bounds);}if(bounds.outWidth<=0||bounds.outHeight<=0)throw new IOException("Choose a readable photo.");
        BitmapFactory.Options options=new BitmapFactory.Options();options.inSampleSize=1;while(Math.max(bounds.outWidth,bounds.outHeight)/options.inSampleSize>2880)options.inSampleSize*=2;Bitmap decoded;try(InputStream in=getContentResolver().openInputStream(uri)){decoded=BitmapFactory.decodeStream(in,null,options);}if(decoded==null)throw new IOException("This image could not be opened.");
        Matrix matrix=new Matrix();try(InputStream in=getContentResolver().openInputStream(uri)){int orientation=new ExifInterface(in).getAttributeInt(ExifInterface.TAG_ORIENTATION,1);switch(orientation){case 2:matrix.setScale(-1,1);break;case 3:matrix.setRotate(180);break;case 4:matrix.setScale(1,-1);break;case 5:matrix.setRotate(90);matrix.postScale(-1,1);break;case 6:matrix.setRotate(90);break;case 7:matrix.setRotate(270);matrix.postScale(-1,1);break;case 8:matrix.setRotate(270);break;}}catch(IOException ignored){}
        Bitmap oriented=Bitmap.createBitmap(decoded,0,0,decoded.getWidth(),decoded.getHeight(),matrix,true);if(oriented!=decoded)decoded.recycle();float scale=Math.min(1f,1440f/Math.max(oriented.getWidth(),oriented.getHeight()));Bitmap image=Bitmap.createScaledBitmap(oriented,Math.max(1,Math.round(oriented.getWidth()*scale)),Math.max(1,Math.round(oriented.getHeight()*scale)),true);if(image!=oriented)oriented.recycle();String photo=id("photo");File file=store.photo(photo);try{for(int quality=82;quality>=42;quality-=10){try(FileOutputStream out=new FileOutputStream(file)){if(!image.compress(Bitmap.CompressFormat.JPEG,quality,out))throw new IOException("Photo conversion failed.");}if(file.length()<=2*1024*1024)break;}if(file.length()>2*1024*1024)throw new IOException("Photo is too large. Choose a simpler image.");}finally{image.recycle();}return photo;
    },photo->{if(draft!=target)return;Catalog.put(draft,"photoId",photo);draft.remove("wasteAssessment");draft.remove("wasteDecision");selectedCodes.clear();dirty=true;photoError="";assessmentLoading=false;render();if(!workspaceCode.isEmpty())assessPhoto();},error->{if(draft==target){photoError=message(error);renderPhotoPanel();}});}
    void assessPhoto(){if(draft==null||assessmentLoading)return;if(workspaceCode.isEmpty()){connectionDialog();return;}String photo=draft.optString("photoId");if(photo.isEmpty()){alert("Add a photo","Take or choose a photo first.");return;}JSONObject target=draft;String code=workspaceCode;assessmentLoading=true;photoError="";renderPhotoPanel();task(()->{File file=store.photo(photo);if(!file.exists())api.download(photo,code,file);api.upload(file,photo,code);JSONObject body=new JSONObject();body.put("photoId",photo);JSONObject result=api.json("POST","/api/lot-assessments",code,body);if(!photo.equals(result.optString("photoId"))||!result.optString("scope").equals("broad"))throw new IOException("Assessment did not match the photo.");return result;},result->{if(draft!=target||!draft.optString("photoId").equals(photo))return;Catalog.put(draft,"wasteAssessment",result);draft.remove("wasteDecision");selectedCodes=Catalog.suggested(result);assessmentLoading=false;dirty=true;renderPhotoPanel();},error->{if(draft==target&&draft.optString("photoId").equals(photo)){assessmentLoading=false;photoError=message(error);renderPhotoPanel();}});}
    private void showPhoto(LinearLayout parent,String photoId){ImageView image=new ImageView(this);image.setContentDescription("Lot photo");image.setScaleType(ImageView.ScaleType.FIT_CENTER);parent.addView(image,new LinearLayout.LayoutParams(-1,dp(200)));File file=store.photo(photoId);if(file.exists()){image.setImageURI(Uri.fromFile(file));return;}if(!workspaceCode.isEmpty())task(()->{api.download(photoId,workspaceCode,file);return file;},loaded->{if(image.isAttachedToWindow())image.setImageURI(Uri.fromFile(loaded));},error->{image.setContentDescription("Photo unavailable");});}

    private void saveDraft(){if(draft==null)return;try{Catalog.put(draft,"updatedAt",now());store.saveDraft(draft);dirty=false;detailId=draft.optString("id");draft=null;screen="detail";render();toast("Draft saved on this device");}catch(Exception error){alert("Could not save",message(error));}}
    private void publishLot(){if(draft==null||working)return;if(assessmentLoading){alert("Identification is running","Wait for the result before listing, or save a draft.");return;}if(draft.optString("materialId").isEmpty()){alert("Pricing material required","Choose a supported pricing material to list, or save this equipment as a draft.");return;}String weight=draft.optString("weight");if(!weight.matches("\\d+(\\.\\d{1,3})?")||Double.parseDouble(weight)<=0||Double.parseDouble(weight)>50000){alert("Check weight","Enter a positive weight up to 50,000 kg, with at most three decimals.");return;}if(draft.optString("photoId").isEmpty()){alert("Add a photo","Take or choose a photo first.");return;}JSONObject decision=draft.optJSONObject("wasteDecision");if(draft.optJSONObject("wasteAssessment")!=null&&decision==null){alert("Confirm the categories","Review and confirm the photo categories before listing.");return;}if(decision!=null&&decision.optString("outcome").equals("retake_photo")){alert("Replace the photo","Take or upload a clearer photo before listing.");return;}if(workspaceCode.isEmpty()){connectionDialog();return;}
        JSONObject lot=Catalog.copy(draft),input=new JSONObject();for(String key:new String[]{"id","materialId","weight","locality","condition","description","photoId","wasteAssessment","wasteDecision"})if(lot.has(key))Catalog.put(input,key,lot.opt(key));if(lot.optString("status").equals("listed")&&lot.has("version"))Catalog.put(input,"expectedVersion",lot.optInt("version"));JSONObject command=new JSONObject(),pending=new JSONObject();Catalog.put(command,"type","list");Catalog.put(command,"input",input);Catalog.put(pending,"operationId",id("operation"));Catalog.put(pending,"command",command);Catalog.put(lot,"pendingCommand",pending);Catalog.put(lot,"updatedAt",now());try{store.saveDraft(lot);dirty=false;draft=null;detailId=lot.optString("id");screen="detail";sendPending(lot);}catch(Exception error){alert("Could not save",message(error));}}
    private void sendPending(JSONObject lot){if(working)return;if(workspaceCode.isEmpty()){connectionDialog();return;}working=true;render();String code=workspaceCode;task(()->{String photo=lot.optString("photoId");api.upload(store.photo(photo),photo,code);api.json("POST","/api/commands",code,lot.getJSONObject("pendingCommand"));JSONObject state=api.json("GET","/api/state",code,null).getJSONObject("state");store.setShared(state);store.removeDraft(lot.optString("id"));return state;},state->{shared=state;working=false;screen="detail";render();toast("Lot listed and synchronized");},error->{working=false;render();alert("Saved for retry",message(error)+" Your local lot is retained. Use Retry listing.");});}

    private void detailView(){JSONObject lot=findLot(detailId);if(lot==null){add(page,text("Lot not found",22,INK,true));return;}action(page,"‹ My lots","back-lots",()->leaveFor("lots"),false);add(page,text(Catalog.title(lot),25,INK,true));add(page,text(lot.optString("status","draft").toUpperCase(Locale.ROOT)+" · "+lot.optString("locality"),14,GREEN,true));LinearLayout c=card(page);String photo=lot.optString("photoId");if(!photo.isEmpty())showPhoto(c,photo);add(c,text(lot.optString("weight","").isEmpty()?"Weight not recorded":lot.optString("weight")+" kg",18,INK,true));add(c,text("Pricing material: "+Catalog.material(lot.optString("materialId")),14,MUTED,false));if(!lot.optString("description").isEmpty())add(c,text(lot.optString("description"),16,INK,false));JSONObject decision=lot.optJSONObject("wasteDecision"),assessment=lot.optJSONObject("wasteAssessment");if(decision!=null){add(c,text("Confirmed photo categories",17,GREEN,true));add(c,text(decisionLabel(decision),16,INK,true));add(c,text("Human decision: "+decision.optString("method"),13,MUTED,false));}if(assessment!=null){add(c,text("Gemini assessment",17,GREEN,true));add(c,text(assessment.optString("description"),15,INK,false));add(c,text(assessment.optString("uncertainty"),13,MUTED,false));add(c,text(assessment.optString("model"),12,MUTED,false));}if(lot.has("pendingCommand"))action(page,"Retry listing","retry-listing",()->sendPending(lot),true);else if(Arrays.asList("draft","listed").contains(lot.optString("status")))action(page,"Edit lot","edit-lot",()->editLot(lot),true);if(lot.optString("status").equals("listed")&&!lot.has("pendingCommand"))offersView(lot);add(page,text("Photo categories do not determine the price. Existing shared sales and payments remain on the connected workspace.",13,MUTED,false));}
    private void offersView(JSONObject lot){LinearLayout box=card(page);add(box,text("Buyer offers",20,INK,true));add(box,text("Demo offers only. No money is transferred.",13,MUTED,false));JSONArray offers=shared.optJSONArray("offers");boolean any=false;if(offers!=null)for(int i=0;i<offers.length();i++){JSONObject offer=offers.optJSONObject(i);if(offer!=null&&offer.optString("lotId").equals(lot.optString("id"))){any=true;add(box,text(offer.optString("buyerId")+" · "+money(offer.optDouble("ratePaise"))+" / kg · "+offer.optString("status"),15,INK,false));if(offer.optString("status").equals("pending"))action(box,"Accept this offer","accept-offer",()->new AlertDialog.Builder(this).setTitle("Accept demo offer?").setMessage(money(offer.optDouble("ratePaise"))+" per kg. Final value uses confirmed weight.").setPositiveButton("Accept",(d,w)->{JSONObject input=new JSONObject();Catalog.put(input,"offerId",offer.optString("id"));command("accept",lot,input);}).setNegativeButton("Cancel",null).show(),false);}}if(!any)add(box,text("No offers yet.",14,MUTED,false));String material=lot.optString("materialId"),locality=lot.optString("locality");if(Arrays.asList("Mumbai","Thane").contains(locality))action(box,"Request Green Loop demo offer","request-offer",()->{JSONObject input=new JSONObject();Catalog.put(input,"buyerId","buyer-green");command("offer",lot,input);},false);else if(Arrays.asList("cables","motors").contains(material))action(box,"Request Circular Metals demo offer","request-offer",()->{JSONObject input=new JSONObject();Catalog.put(input,"buyerId","buyer-circle");command("offer",lot,input);},false);else action(box,"Request Board Recovery demo offer","request-offer",()->{JSONObject input=new JSONObject();Catalog.put(input,"buyerId","buyer-board");command("offer",lot,input);},false);}
    private void command(String type,JSONObject lot,JSONObject input){if(working)return;if(workspaceCode.isEmpty()){connectionDialog();return;}JSONObject command=new JSONObject(),body=new JSONObject();Catalog.put(command,"type",type);Catalog.put(command,"lotId",lot.optString("id"));Catalog.put(command,"expectedVersion",lot.optInt("version"));Catalog.put(command,"input",input);Catalog.put(body,"operationId",id("operation"));Catalog.put(body,"command",command);working=true;render();task(()->{api.json("POST","/api/commands",workspaceCode,body);JSONObject state=api.json("GET","/api/state",workspaceCode,null).getJSONObject("state");store.setShared(state);return state;},state->{shared=state;working=false;render();},error->{working=false;render();alert("Could not update",message(error));});}
    private void walletView(){add(page,text("Earnings",27,INK,true));JSONArray payments=shared.optJSONArray("payments");double total=0;if(payments!=null)for(int i=0;i<payments.length();i++){JSONObject p=payments.optJSONObject(i);if(p!=null&&p.optString("status").equals("confirmed"))total+=p.optDouble("amountPaise");}LinearLayout c=card(page);add(c,text("Confirmed payments in your workspace",15,MUTED,false));add(c,text(money(total),32,GREEN,true));add(c,text("Demo records only. No actual money is transferred.",13,MUTED,false));action(page,"Refresh workspace","refresh-wallet",()->refreshWorkspace(true),false);}

    private void connectionDialog(){LinearLayout fields=column();fields.setPadding(dp(24),dp(6),dp(24),dp(8));add(fields,text("Connect to your shared workspace to use Gemini and synchronize lots. Your Gemini API key stays on the backend.",15,INK,false));EditText input=new EditText(this);input.setHint("Workspace pairing code");input.setContentDescription("Workspace pairing code");input.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD);input.setSingleLine(true);add(fields,input);add(fields,text("Native Android 1.0 · "+ApiClient.ORIGIN,12,MUTED,false));AlertDialog dialog=new AlertDialog.Builder(this).setTitle("Workspace connection").setView(fields).setPositiveButton("Connect",null).setNegativeButton("Cancel",null).create();dialog.setOnShowListener(v->dialog.getButton(AlertDialog.BUTTON_POSITIVE).setOnClickListener(view->{String code=input.getText().toString().trim();if(!code.matches("[a-f0-9]{48}")){input.setError("Enter the 48-character workspace code.");return;}dialog.getButton(AlertDialog.BUTTON_POSITIVE).setEnabled(false);task(()->{JSONObject state=api.json("GET","/api/state",code,null).getJSONObject("state");store.setCode(code);store.setShared(state);return state;},state->{workspaceCode=code;shared=state;dialog.dismiss();render();if(screen.equals("create")&&draft!=null&&!draft.optString("photoId").isEmpty())assessPhoto();},error->{dialog.getButton(AlertDialog.BUTTON_POSITIVE).setEnabled(true);input.setError(message(error));});}));dialog.show();}
    private void refreshWorkspace(boolean notify){if(workspaceCode.isEmpty()){if(notify)connectionDialog();return;}String code=workspaceCode;task(()->{JSONObject state=api.json("GET","/api/state",code,null).getJSONObject("state");store.setShared(state);return state;},state->{shared=state;if(!screen.equals("create"))render();if(notify)toast("Workspace refreshed");},error->{if(notify)alert("Connection unavailable",message(error)+" Local drafts are still available.");});}
}
